/**
 */
package security.securityThreats.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import security.securityThreats.util.SecurityThreatsAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SecurityThreatsItemProviderAdapterFactory extends SecurityThreatsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SecurityThreatsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.ThreatCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThreatCatalogItemProvider threatCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.ThreatCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThreatCatalogAdapter() {
		if (threatCatalogItemProvider == null) {
			threatCatalogItemProvider = new ThreatCatalogItemProvider(this);
		}

		return threatCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.AttackerClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackerClassItemProvider attackerClassItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.AttackerClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackerClassAdapter() {
		if (attackerClassItemProvider == null) {
			attackerClassItemProvider = new AttackerClassItemProvider(this);
		}

		return attackerClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.Attack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttackItemProvider attackItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.Attack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttackAdapter() {
		if (attackItemProvider == null) {
			attackItemProvider = new AttackItemProvider(this);
		}

		return attackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.ComponentAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentAttackItemProvider componentAttackItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.ComponentAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAttackAdapter() {
		if (componentAttackItemProvider == null) {
			componentAttackItemProvider = new ComponentAttackItemProvider(this);
		}

		return componentAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.SystemAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemAttackItemProvider systemAttackItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.SystemAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemAttackAdapter() {
		if (systemAttackItemProvider == null) {
			systemAttackItemProvider = new SystemAttackItemProvider(this);
		}

		return systemAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.ResourceAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourceAttackItemProvider resourceAttackItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.ResourceAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourceAttackAdapter() {
		if (resourceAttackItemProvider == null) {
			resourceAttackItemProvider = new ResourceAttackItemProvider(this);
		}

		return resourceAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.AllocationAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllocationAttackItemProvider allocationAttackItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.AllocationAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllocationAttackAdapter() {
		if (allocationAttackItemProvider == null) {
			allocationAttackItemProvider = new AllocationAttackItemProvider(this);
		}

		return allocationAttackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link security.securityThreats.UsageAttack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsageAttackItemProvider usageAttackItemProvider;

	/**
	 * This creates an adapter for a {@link security.securityThreats.UsageAttack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUsageAttackAdapter() {
		if (usageAttackItemProvider == null) {
			usageAttackItemProvider = new UsageAttackItemProvider(this);
		}

		return usageAttackItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (threatCatalogItemProvider != null) threatCatalogItemProvider.dispose();
		if (attackerClassItemProvider != null) attackerClassItemProvider.dispose();
		if (attackItemProvider != null) attackItemProvider.dispose();
		if (componentAttackItemProvider != null) componentAttackItemProvider.dispose();
		if (systemAttackItemProvider != null) systemAttackItemProvider.dispose();
		if (resourceAttackItemProvider != null) resourceAttackItemProvider.dispose();
		if (allocationAttackItemProvider != null) allocationAttackItemProvider.dispose();
		if (usageAttackItemProvider != null) usageAttackItemProvider.dispose();
	}

}
